config/routes.rb
CeneoScrapper::Application.routes.draw do
  root :to => "home#index"

  put "/set_current_shop", to: "home#set_current_shop", as: :set_current_shop

  resources :producers do
    get :products, to: "products#producer_products_index"
    collection do
      post :import
    end
  end

  resources :collections do
    get :products, to: "products#collection_products_index"
    collection do
      post :import
    end
  end

  resources :products do
    member do
      get :refresh
    end
    collection do
      get :refresh_collection
    end
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :producer
  belongs_to :make
  has_many :products

  attr_accessible :mask,
                  :name,
                  :page_count,
                  :url

  validates :name, uniqueness: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Collection.create! row.to_hash
    end
  end

  def to_s
    self.name
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  
  def index
    @collections = Collection.order("name asc").all
  end

  def new
    @collection = Collection.new
    render "show"
  end

  def create
    @collection = Collection.new(params[:collection])
    if @collection.save
      redirect_to collections_path, notice: "Stworzono nową kolekcję - #{@collection.name}"
    else
      @collection
      flash.now[:alert] = "Popraw dane"
      render "show"
    end
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def edit
    @collection = Collection.find(params[:id])
    render "show"
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(params[:collection])
      redirect_to collections_path, notice: "Zaktualizowano kolekcję - #{@collection.name}"
    else
      @collection
      flash.now[:alert] = "Popraw dane"
      render "show"
    end
  end

  def destroy
    Collection.find(params[:id]).destroy
    redirect_to collections_path, notice: "Kolekcja usunięta"
  end

  def import
    Collection.import(params[:file])
    redirect_to collections_url, notice: "Kolekcje zaimportowane"
  end
end

app/views/collections/index.html.haml
%h1 Kolekcje
= link_to new_collection_path do
  %button.btn Dodaj nową

%table
  %thead
    %tr
      %th Nazwa
      %th Producent
      %th Ilość produktów
      %th Edytuj
      %th Usuń
  %tbody
    - @collections.each do |collection|
      %tr
        %td= collection.name
        %td= collection.producer
        %td
          - if collection.products.count > 0
            = link_to collection.products.count, collection_products_path(collection)
        %td
          = link_to "Edytuj", edit_collection_path(collection)
        %td
          = link_to "Usuń", collection_path(collection), method: :delete, confirm: "Na pewno chcesz usunąć kategorię #{collection.name}?"

%h3 Importuj z pliku
= form_tag import_collections_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Importuj"

app/views/collections/show.html.haml
= simple_form_for @collection do |f|
  = f.input :name, label: "Nazwa"
  = f.submit "Zapisz", class: "btn btn-success"

= link_to collections_path do
  %button.btn Anuluj