config/routes.rb
CeneoScrapper::Application.routes.draw do
  root :to => "home#index"

  put "/set_current_shop", to: "home#set_current_shop", as: :set_current_shop

  resources :producers do
    get :products, to: "products#producer_products_index"
    collection do
      post :import
    end
  end

  resources :collections do
    get :products, to: "products#collection_products_index"
    collection do
      post :import
    end
  end

  resources :products do
    member do
      get :refresh
    end
    collection do
      get :refresh_collection
    end
  end
end

app/models/producer.rb
class Producer < ActiveRecord::Base

  extend  CeneoFetcher::ProducersFetcher

  has_many :makes
  has_many :collections
  has_many :products

  attr_accessible :kh_kod,
                  :mask,
                  :name,
                  :page_count

  validates :name, uniqueness: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Producer.create row.to_hash
    end
  end

  def to_s
    self.name
  end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  
  def index
    @producers = Producer.order("name asc").all
  end

  def new
    @producer = Producer.new
    render "show"
  end

  def create
    @producer = Producer.new(params[:producer])
    if @producer.save
      redirect_to producers_path, notice: "Stworzono nowego producenta - #{@producer.name}"
    else
      @producer
      flash.now[:alert] = "Popraw dane"
      render "show"
    end
  end

  def show
    @producer = Producer.find(params[:id])
  end

  def edit
    @producer = Producer.find(params[:id])
    render "show"
  end

  def update
    @producer = Producer.find(params[:id])
    if @producer.update_attributes(params[:producer])
      redirect_to producers_path, notice: "Zaktualizowano producenta - #{@producer.name}"
    else
      @producer
      flash.now[:alert] = "Popraw dane"
      render "show"
    end
  end

  def destroy
    Producer.find(params[:id]).destroy
    redirect_to producers_path, notice: "Producent usunięty"
  end

  def import
    Producer.import(params[:file])
    redirect_to producers_url, notice: "Producenci zaimportowani"
  end
end

app/views/producers/index.html.haml
%h1 Producenci
= link_to new_producer_path do
  %button.btn Dodaj nowego

%table
  %thead
    %tr
      %th Nazwa
      %th Ilość kolekcji
      %th Ilość produktów
      %th Najlepszych ofert
      %th Edytuj
      %th Usuń
  %tbody
    - @producers.each do |producer|
      %tr
        %td= producer
        %td
          - if producer.collections.count > 0
            = producer.collections.count
        %td
          - if producer.products.count > 0
            = link_to producer.products.count, producer_products_path(producer)
        %td
          N/A
        %td
          = link_to "Edytuj", edit_producer_path(producer)
        %td
          = link_to "Usuń", producer_path(producer), method: :delete, confirm: "Na pewno chcesz usunąć producenta #{producer.name}?"

%h3 Importuj z pliku
= form_tag import_producers_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Importuj"

app/views/producers/show.html.haml
= simple_form_for @producer do |f|
  = f.input :name, label: "Nazwa"
  = f.submit "Zapisz", class: "btn btn-success"

= link_to producers_path do
  %button.btn Anuluj