config/routes.rb
CeneoScrapper::Application.routes.draw do
  root :to => "home#index"

  put "/set_current_shop", to: "home#set_current_shop", as: :set_current_shop

  resources :producers do
    get :products, to: "products#producer_products_index"
    collection do
      post :import
    end
  end

  resources :collections do
    get :products, to: "products#collection_products_index"
    collection do
      post :import
    end
  end

  resources :products do
    member do
      get :refresh
    end
    collection do
      get :refresh_collection
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  extend CeneoFetcher::ProductsFetcher

  belongs_to :producer
  belongs_to :category
  belongs_to :collection
  has_many :data_sets

  attr_accessible :base_list_url,
                  :collection_id,
                  :listing_id,
                  :mask,
                  :name,
                  :producer_id,
                  :remaining_list_url

  validates :name, uniqueness: true

  def match_producer
    self.producer = find_producer
    self.save
    self.reload
  end

  def latest_offers
    return nil unless self.data_sets.exists?
    self.data_sets.latest_one.offers
  end

  def to_s
    self.name
  end

  def products_from_collection
    return [] unless self.collection
    #TODO - refactor
    self.collection.products.where("id != ?", self.id).order("LOWER(name)")
  end

  def self.similar_products_for(product)
    #TODO - refactor
    ret = []
    ret << Product.where("name ilike ?", "#{product.name.split(/\s+/, 5)[0...4].join(' ')}%").all - [product]
    ret << Product.where("name ilike ?", "#{product.name.split(/\s+/, 4)[0...3].join(' ')}%").all - ret.flatten - [product]
    ret << Product.where("name ilike ?", "#{product.name.split(/\s+/, 3)[0...2].join(' ')}%").all - ret.flatten - [product]
    ret.flatten
  end

  private

  def find_producer
    producer = self.class.match_product_producer_from(self.name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    respond_to do |format|
      format.html { @products, @alphaParams = Product.order("name asc").all.alpha_paginate(params[:letter]){ |product| product.name} }
      format.xls  { @products = Product.order("name asc") }
    end
  end

  def show
    @product = Product.includes(:producer, :collection, :data_sets).find(params[:id])
    @data_sets = @product.data_sets.order("created_at DESC").limit(10).reverse
    @products_from_collection = @product.products_from_collection
    @similar_products = Product.similar_products_for(@product)
  end

  def update
    @product = Product.find(params[:id])
    attrs = case params[:commit]
            when "Zmień producenta"
              params[:product].except(:collection_id)
            when "Zmień kolekcję"
              params[:product].except(:producer_id)
            end
    if @product.update_attributes(attrs)
      if params[:with_selected_products]
        update_selected_products(params[:products_to_update].split(","), attrs)
      end
      redirect_to product_path(@product), notice: "Zapisano zmiany w produkcie"
    else
      @product
      flash.now[:error] = "Nie można zapisać zmian"
      render 'show'
    end
  end

  def producer_products_index
    @producer = Producer.find(params[:producer_id])
    @products = @producer.products.order("products.name asc").all
    render :index
  end

  def collection_products_index
    @collection = Collection.find(params[:collection_id])
    @products = @collection.products.order("products.name asc").all
    render :index
  end

  def refresh
    product = Product.find(params[:id])
    product.data_sets.create.offers << Offer.fetch_offers_for(product, true)
    find_proper_collection
    if @products
      render :index
    else
      redirect_to product_path(product)
    end
  end

  def refresh_collection
    find_proper_collection
    Offer.fetch_offers_for(@products, true) 
    find_proper_collection
    render :index
  end

  def destroy
    Producer.find(params[:id]).destroy
    redirect_to products_path, notice: "Producent usunięty"
  end

  def find_proper_collection
    if params[:producer_id].presence
      @producer = Producer.find(params[:producer_id])
      @products = @producer.products.order("products.name asc").all
    end
    if params[:collection_id].presence
      @collection = Collection.find(params[:collection_id])
      @products = @collection.products.order("products.name asc").all
    end
    if params[:letter].presence
      @products, @alphaParams = Product.order("name asc").all.alpha_paginate(params[:letter]){ |product| product.name} if params[:letter]
    end
  end

  private

  def update_selected_products(ids, attrs)
    ids.each do |product_id|
      unless Product.find(product_id).update_attributes(attrs)
        flash.now[:error] = "Nie można zapisać zmian dla jednego z zaznaczonych produktów o id: #{product_id} - produkt który widzisz na tej stronie został jednak zapisany!"
        render 'show' and return
      end
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def price_spread(prices)
    [prices[0], prices[-1]]
  end

  def position_for_shop(shop, prices)
    return nil unless prices
    index = index_for_shop(shop, prices)
    index ? index + 1 : "brak"
  end

  def difference_from_best(shop, prices)
    return nil unless prices
    index = index_for_shop(shop, prices)
    return nil unless index
    ((prices[index][1] - prices[0][1]) / 100.0).to_s + " zł"
  end

  def percentage_difference_from_best(shop, prices)
    return nil unless prices
    index = index_for_shop(shop, prices)
    return nil unless index
    (((((prices[index][1] * 1.0) / prices[0][1])) - 1) * 100).round(1).to_s + " %"
  end

  def index_for_shop(shop, prices)
    prices.index{ |price| price[0] == shop.name } 
  end

end

app/views/products/index.html.haml
%h1 Produkty
%span
  = link_to "Pobierz wszystkie jako XLS", products_path(producer_id: @producer.try(:id), collection_id: @producer.try(:id), format: :xls)
- if @collection
  %h2
    Kolekcja: #{@collection}
- if @producer
  %h2
    Producent: #{@producer}

- if @alphaParams
  = alphabetical_paginate @alphaParams

= link_to "Odśwież wszystkie z tej strony", refresh_collection_products_path( producer_id: @producer.try(:id), collection_id: @collection.try(:id), letter: params[:letter] )

%table#pagination_table
  %thead
    %tr
      %th Nazwa
      %th Link
      - unless @producer
        %th Producent
      - unless @collection
        %th Kolekcja
      %th Ilość ofert
      %th Rozpiętość cenowa
      %th Najtańsza oferta
      - if @shop = Shop.find_by_id(session[:current_shop_id])
        %th Pozycja #{@shop}
        %th{ colspan: 2} Różnica #{@shop} względem najtańszej
      %th Odśwież
  %tbody
    - @products.each do |product|
      %tr
        %td
          = link_to product, product_path(product)
        %td
          = link_to "Link", [ROADMAP[:ceneo][:url], product.base_list_url].join, target: :blank
        - unless @producer
          %td= product.producer
        - unless @collection
          %td= product.collection
        %td= product.latest_offers.try(:count)
        - @prices = product.data_sets.latest_one.try(:prices)
        %td
          - if @prices
            = price_spread(@prices).try(:compact).try(:size) == 2 ? "#{price_spread(@prices)[0][1] / 100.0} zł - #{price_spread(@prices)[1][1] / 100.0} zł" : ""
        %td
          - if @prices
            = price_spread(@prices).try(:compact).try(:size) == 2 ? "#{price_spread(@prices)[0][1] / 100.0} zł - #{price_spread(@prices)[0][0]}" : ""
        - if @shop
          %td
            = position_for_shop(@shop, @prices)
          %td
            = difference_from_best(@shop, @prices)
          %td
            = percentage_difference_from_best(@shop, @prices)
          %td
            = link_to "Odśwież", refresh_product_path(product, producer_id: @producer.try(:id), collection_id: @collection.try(:id), letter: params[:letter] )

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="dupa">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nazwa</Data></Cell>
        <Cell><Data ss:Type="String">Producent</Data></Cell>
        <Cell><Data ss:Type="String">Kolekcja</Data></Cell>
        <Cell><Data ss:Type="String">Ilość Ofert</Data></Cell>
        <Cell><Data ss:Type="String">Ropiętość Cenowa</Data></Cell>
        <Cell><Data ss:Type="String">Najtańsza Oferta</Data></Cell>
        <Cell><Data ss:Type="String">Pozycja</Data></Cell>
        <Cell><Data ss:Type="String">Różnica względem najtańszej</Data></Cell>
      </Row>
    <% @shop = Shop.find_by_id(session[:current_shop_id]) %>

    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.producer %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.collection %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.latest_offers.try(:count) %></Data></Cell>
        <% @prices = product.data_sets.latest_one.try(:prices) %>
        <% if @prices %>
          <Cell><Data ss:Type="String"><%= price_spread(@prices).try(:compact).try(:size) == 2 ? "#{price_spread(@prices)[0][1] / 100.0} zł - #{price_spread(@prices)[1][1] / 100.0} zł" : "" %></Data></Cell>
          <Cell><Data ss:Type="String"><%= price_spread(@prices).try(:compact).try(:size) == 2 ? "#{price_spread(@prices)[0][1] / 100.0} zł - #{price_spread(@prices)[0][0]}" : "" %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="String"><%= position_for_shop(@shop, @prices) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= difference_from_best(@shop, @prices) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= percentage_difference_from_best(@shop, @prices) %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/show.html.haml
#product
  %h1 #{@product}
  .product-offers
    %h3 
      Historia ofert
      = link_to refresh_product_path(@product) do
        %button.btn Pobierz nowe oferty
    %span (maks. ostatnich 10 ofert)
    %table
      %thead
        %tr
          %th Data
          %th Ilość ofert
          %th Rozpiętość cenowa
          %th Najtańsza oferta
          - if @shop = Shop.find_by_id(session[:current_shop_id])
            %th Pozycja #{@shop}
            %th{ colspan: 2} Różnica #{@shop} względem najtańszej
      %tbody
        - @data_sets.each do |data_set|
          %tr
            %td= l data_set.created_at, format: :short
            %td= data_set.offers.count
            - @prices = data_set.prices
            %td
              - if @prices
                = price_spread(@prices).try(:compact).try(:size) == 2 ? "#{price_spread(@prices)[0][1] / 100.0} zł - #{price_spread(@prices)[1][1] / 100.0} zł" : ""
            %td
              - if @prices
                = price_spread(@prices).try(:compact).try(:size) == 2 ? "#{price_spread(@prices)[0][1] / 100.0} zł - #{price_spread(@prices)[0][0]}" : ""
            - if @shop
              %td
                = position_for_shop(@shop, @prices)
              %td
                = difference_from_best(@shop, @prices)
              %td
                = percentage_difference_from_best(@shop, @prices)
  .product-actions
    = simple_form_for @product do |f|
      = hidden_field_tag :products_to_update, nil, class: "products-to-update"
      .product-producer-info
        %h3 Producent
        = f.association :producer, label: false
        = f.submit 'Zmień producenta'
        = check_box_tag :with_selected_products
        Wraz z zaznaczonymi
      .product-collection-info
        %h3 Kolekcja
        = f.association :collection, label: false
        = f.submit 'Zmień kolekcję'
        = check_box_tag :with_selected_products
        Wraz z zaznaczonymi
  .other-products
    .products-from-collection
      - if @products_from_collection.any?
        %h3 Pozostałe produkty kolekcji
        = select_tag @product, options_from_collection_for_select(@products_from_collection, :id, :name), { multiple: true, size: @products_from_collection.count, class: "products-select" }
    .similar-products
      - if @similar_products.any?
        %h3 Podobne produkty
        = select_tag @product, options_from_collection_for_select(@similar_products, :id, :name), { multiple: true, size: @similar_products.count, class: "products-select" }