config/routes.rb
CeneoScrapper::Application.routes.draw do
  root :to => "home#index"

  put "/set_current_shop", to: "home#set_current_shop", as: :set_current_shop

  resources :producers do
    get :products, to: "products#producer_products_index"
    collection do
      post :import
    end
  end

  resources :collections do
    get :products, to: "products#collection_products_index"
    collection do
      post :import
    end
  end

  resources :products do
    member do
      get :refresh
    end
    collection do
      get :refresh_collection
    end
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Ceneo Scrapper", root_path, :class => 'brand'
= link_to "Producenci", producers_path
= link_to "Kolekcje", collections_path
= link_to "Produkty", products_path
= select_tag "shops", options_from_collection_for_select(Shop.order("LOWER(name) ASC"), :id, :name, session[:current_shop_id]), { prompt: "wybierz sklep" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= "Scrapper - " + @title
      %meta{:content => content_for?(:description) ? yield(:description) : "Ceneo Scrapper", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span14
              = render 'layouts/messages'
              = yield
          %footer